language: cpp

sudo: required
dist: trusty

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-5
    - g++-5
    - clang-3.7
    - cmake
    - cmake-data
    - libboost-all-dev

matrix:
  include:
    - compiler: gcc-5
      env: CC=gcc-5 CXX=g++-5
    - compiler: clang-3.7
      env: CC=clang-3.7 CXX=clang++-3.7

before_script:
- cmake . -DMCRL2_ENABLE_GUI_TOOLS=OFF -DMCRL2_ENABLE_EXPERIMENTAL=ON

script:
- make
#- ctest -E "random|headertest" --output-on-failure

